Return first version with push --force
markoff96/sneaker_store pull request #2
Opened 2023-02-26 11:31 UTC by markoff96

2023-02-26 11:57 UTC, RomanAchilov requested changes
В целом молодец

2023-02-26 11:57 UTC, RomanAchilov commented on src/App.js
> +      .then((res) => res.json())
Use async await instead .then

2023-02-26 11:57 UTC, RomanAchilov commented on src/components/Body.jsx
> +function Body() {
Отступ от импортов сделай, а мог линтеры настроить

2023-02-26 11:57 UTC, RomanAchilov commented on src/components/Card.jsx
> +    <div className="cards">
Компонент card а класс нейм cards

2023-02-26 11:57 UTC, RomanAchilov commented on src/components/Card.jsx
> +      <img width={200} height={200} src="/img/sneakers1.jpeg" alt="cartImg" />
Ну слепым такой alt не особо поможет)

2023-02-26 11:57 UTC, RomanAchilov commented on src/components/Card.jsx
> +      <p>Кроссовки мужские NIKE</p>
Так понимаю в курсе это пропсами еще не делали

2023-02-26 11:57 UTC, RomanAchilov commented on src/components/Header.jsx
> +        <img width={60} height={50} src="/img/logo.png" alt="" />
Пустой алт каеф

2023-02-26 11:57 UTC, RomanAchilov commented on src/components/Header.jsx
> +        <img width={60} height={50} src="/img/logo.png" alt="" />
Почитай так же за webp and avif, а то jpeg и png в 2023 как то не то совсем

2023-02-26 11:57 UTC, RomanAchilov commented on src/index.css
> +.headerSearch {
Имена стилей конечно такие себе, почитай за утилити класса в tailwind и за BEM от яндекс для стилизации. Также ты уже в мире реакта и компонентов и писать все стили в одном файле не оч хорошо.
Т.е. у тебя должна быть папка header, а в ней index.tsx для экспорта твоего компонента, header.tsx для самого компонента и header.css для стилей

2023-02-27 08:56 UTC, markoff96 commented on src/App.js
> +      .then((res) => res.json())
поменял

2023-02-27 09:00 UTC, markoff96 commented on src/components/Body.jsx
> +function Body() {
сделал, мне еслинт на эту тему не ругается((

2023-02-27 09:02 UTC, markoff96 commented on src/components/Card.jsx
> +    <div className="cards">
поменял на card

2023-02-27 09:02 UTC, markoff96 commented on src/components/Card.jsx
> +      <p>Кроссовки мужские NIKE</p>
да первый Варик для верстки, сейчас пропсами

2023-02-27 09:04 UTC, markoff96 commented on src/components/Card.jsx
> +      <img width={200} height={200} src="/img/sneakers1.jpeg" alt="cartImg" />
поменял

2023-02-27 09:09 UTC, markoff96 commented on src/components/Header.jsx
> +        <img width={60} height={50} src="/img/logo.png" alt="" />
alt поменял, webp  формат сжатия изображений, avif улучшеный аналог jpeg

2023-02-27 09:22 UTC, markoff96 commented on src/index.css
> +.headerSearch {
дальше будет перенос стилей по модулям, после попробую перенести на тайлвинд ,за Бэм реакт кор смотрю

2023-02-27 09:24 UTC, markoff96 commented
Разберемся

2023-02-27 09:41 UTC, RomanAchilov commented on src/components/Body.jsx
> +function Body() {
https://gist.github.com/aprilmintacpineda/98263406649de2c5acf316c363391eb6

2023-02-27 09:43 UTC, RomanAchilov approved these changes

2023-02-27 09:43 UTC, RomanAchilov commented on src/App.js
> +      const response = await fetch('https://fakestoreapi.com/products');
Try catch забыл

2023-02-27 12:43 UTC, markoff96 commented on src/components/Body.jsx
> +function Body() {
так точно сэр

2023-02-27 12:44 UTC, markoff96 commented on src/App.js
> +      const response = await fetch('https://fakestoreapi.com/products');
добавил

2023-02-27 12:46 UTC, RomanAchilov approved these changes
Ну все вливай

2023-02-27 13:07 UTC, merged